### ISSUE TITLE
The sampling rate of data is not changing 

### ISSUE THREAD

**Issue by 84rrry** [petri-lipponen-movesense/mdsflutter#10]
I'm facing an issue where the sampling rate of the Accelerometer , Gyroscope and the imu data subscription is always set to **13Hz** whatever the value i set in the URI 
For instance using the Example app which uses **104Hz** **`Mds.createSubscriptionUri(_serial!, "/Meas/Acc/104")`**
results in readings with **Time Stamps** where the difference is always approximately **80ms** which is **`1000/12.5=80`** 
I'm using :
```
- mdsFlutter : 2.0.0
- mdslib : 3.15.0
```

**Comment by petri-lipponen-movesense** [comment]
Each notification can contain multiple samples to save BLE and processing resources. 13Hz: 1 sample, 26: 2, 52: 4 & >=104Hz: 8

The timestamp meaning is defined in the API definition: https://bitbucket.org/movesense/movesense-device-lib/src/984a71234e37bc66cc312b5aba3100ae9a801d97/MovesenseCoreLib/resources/movesense-api/meas/acc.yaml#lines-116
