### ISSUE TITLE
Cocoapods can't access remote repository

### ISSUE THREAD

**Issue by saifrashed** [petri-lipponen-movesense/mdsflutter#13]
When running 'flutter build ios' it outputs the following error:

`Error output from CocoaPods:
↳
         Cloning into
         '/var/folders/0w/_nychjcj46zckst20d9d8lzm0000gn/T/d202
         40114-761-d91zn7'...
         git@altssh.bitbucket.org: Permission denied
         (publickey).
         fatal: Could not read from remote repository.`

Is there a fix for this.

**Comment by saifrashed** [comment]
When using "https://bitbucket.org/movesense/movesense-mobile-lib.git" in the Podfile it does seem to install only to finish off with: 

'Running pod install...                                              8,8s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target
      `Pods-Runner`: (``)

    Fetching external sources
    -> Fetching podspec for `Flutter` from `Flutter`
    -> Pre-downloading: `Movesense` from
    `https://bitbucket.org/movesense/movesense-mobile-lib.git`
     > Git download
     > Git download
         $ /usr/local/bin/git clone
         https://bitbucket.org/movesense/movesense-mobile-lib.g
         it
         /var/folders/0w/_nychjcj46zckst20d9d8lzm0000gn/T/d2024
         0114-1611-fqs7df --template= --single-branch --depth 1
      $ /usr/local/bin/git -C
      /var/folders/0w/_nychjcj46zckst20d9d8lzm0000gn/T/d2024011
      4-1611-fqs7df rev-parse HEAD
      c7cc4933823553d2ad3f67db458c507a633ab33d
      > Copying Movesense from
      `/Users/saifrashed/Library/Caches/CocoaPods/Pods/External
      /Movesense/c4c3887503d4b288f2e8124a5fc7c518` to
      `Pods/Movesense`
    -> Fetching podspec for `mdsflutter` from
    `.symlinks/plugins/mdsflutter/ios`
    -> Fetching podspec for `permission_handler_apple` from
    `.symlinks/plugins/permission_handler_apple/ios`

    Resolving dependencies of `Podfile`
      CDN: trunk Relative path: CocoaPods-version.yml exists!
      Returning local because checking is only performed in
      repo update
    [!] CocoaPods could not find compatible versions for pod
    "mdsflutter":
      In Podfile:
        mdsflutter (from `.symlinks/plugins/mdsflutter/ios`)

    Specs satisfying the `mdsflutter (from
    `.symlinks/plugins/mdsflutter/ios`)` dependency were found,
    but they required a higher minimum deployment target.

    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:317:in
    `raise_error_unless_state'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:299:in `block in
    unwind_for_conflict'
    <internal:kernel>:90:in `tap'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:297:in
    `unwind_for_conflict'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:682:in
    `attempt_to_activate'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:254:in
    `process_topmost_state'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/molinillo
    -0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/resolver.rb:94:in `resolve'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer/analyzer.rb:1082:in `block
    in resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer/analyzer.rb:1080:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer/analyzer.rb:125:in
    `analyze'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer.rb:422:in `analyze'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer.rb:244:in `block in
    resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/user_interface.rb:64:in `section'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer.rb:243:in
    `resolve_dependencies'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/installer.rb:162:in `install!'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/command/install.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/claide-1.
    1.0/lib/claide/command.rb:334:in `run'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/lib/cocoapods/command.rb:52:in `run'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/gems/cocoapods
    -1.14.3/bin/pod:55:in `<top (required)>'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in
    `load'
    /usr/local/Cellar/cocoapods/1.14.3_1/libexec/bin/pod:25:in
    `<main>'

Error output from CocoaPods:
↳
         Cloning into
         '/var/folders/0w/_nychjcj46zckst20d9d8lzm0000gn/T/d202
         40114-1611-fqs7df'...
'

**Comment by bardram** [comment]
I got it to work by using:

`  pod 'Movesense', :git => 'https://bitbucket.org/movesense/movesense-mobile-lib/'`

instead of the ssh verion.

**Comment by Peterkrol12** [comment]
I also used the solution @bardram provided to make it work

**Comment by petri-lipponen-movesense** [comment]
Good to know. It's possible that the bitbucket has changed something in the altssh. We'll change the pod url in the next release. I'll leave this open until it has been fixed.

**Comment by petri-lipponen-movesense** [comment]
Fixed in (coming soon) 2.1.1
