### ISSUE TITLE
Cannot create more than 2 subscription to /System/States

### ISSUE THREAD

**Issue by bardram** [petri-lipponen-movesense/mdsflutter#15]
I want to subscribe to all /System/States events listed at 

* https://www.movesense.com/docs/esw/api_reference/#systemstates

There is a total of 6 possible subscriptions to do for state IDs 0 to 5.

However, once I have created 2 subscriptions, the 3rd creates an error. 

`Failed status: 500, reason: [wb] Operation failed, status: 0`

I have tried different orders of the state IDs, and it always fails at the 3rd subscription. I have also tried using both the `MdsAsync` and `Mds` APIs. Always the same - the 3rd subscription fails.

**Comment by bardram** [comment]
I can add that when trying to subscribe to state id `3` it **always** fails with the error above - also if this is the only subscription attempted.

**Comment by petri-lipponen-movesense** [comment]
Only one movement state (MOVEMENT, TAP, DOUBLETAP, FREEFALL) can be subscribed at the same time (limitation of the underlying hardware).
