### ISSUE TITLE
What device type is "Avocado"?

### ISSUE THREAD

**Issue by bardram** [petri-lipponen-movesense/mdsflutter#16]
When I get device info from the devices we (DTU) got, I get this:

```
{
    "Content": {
        "manufacturerName": "Movesense Ltd",
        "brandName": null,
        "productName": "Movesense",
        "variant": "Avocado",
        "design": "black",
        "hwCompatibilityId": "C",
        "serial": "233830000687",
        "pcbaSerial": "80517336500828200000100022666H4233",
        "sw": "2.1.5",
        "hw": "H4",
        "additionalVersionInfo": null,
        "addressInfo": [
            {
                "name": "BLE",
                "address": "0C-8C-DC-1B-23-3E"
            },
            {
                "name": "DFU-BLE",
                "address": "FC-D9-AC-F3-23-F6"
            }
        ],
        "apiLevel": "1"
    }
}
```

When I ask an `MD` device, I get "MD" - But - what type of device is "Avocado"? HR, HR+, Flash, ...?

**Comment by Peterkrol12** [comment]
Not really an answer, but perhaps try opening these issues on the [Movesense Bitbucket](https://bitbucket.org/movesense/movesense-mobile-lib/issues). The developer, @petri-lipponen-movesense, seems to be more active there

**Comment by petri-lipponen-movesense** [comment]
It's and old project name from times when Movesense was part of Suunto Oy.

**Comment by petri-lipponen-movesense** [comment]
The "hw" -field describes the exact HW model. H3 is "HR+" and H4 is "HR2" IIRC

**Comment by petri-lipponen-movesense** [comment]
> Not really an answer, but perhaps try opening these issues on the [Movesense Bitbucket](https://bitbucket.org/movesense/movesense-mobile-lib/issues). The developer, @petri-lipponen-movesense, seems to be more active there

Please, no. Especially for mdsflutter specific stuff, let's keep it here. Generic movesense questions (like this one) should be probably asked in stackoverflow.com tag [movesense].

**Comment by bardram** [comment]
> The "hw" -field describes the exact HW model. H3 is "HR+" and H4 is "HR2" IIRC

Is there a place where I can see an overview of different hardware types? I also have a type called `A1` (which seems to be the `MD` model)?
