### ISSUE TITLE
Cannot use `use_frameworks!`

### ISSUE THREAD

**Issue by SlimShadyIAm** [petri-lipponen-movesense/mdsflutter#18]
Based on the README documentation, in order to use the `mdsflutter` package we need to remove `use_frameworks!` from our Podfile. However, we have a dependency ([`health`](https://pub.dev/packages/health)) to integrate with Apple HealthKit which requires `use_frameworks!` otherwise the Swift bridging headers are not generated and we get the error:

```
Failed to build iOS app
Lexical or Preprocessor Issue (Xcode): 'health/health-Swift.h' file not found
/Users/<user>/.pub-cache/hosted/pub.dev/health-9.0.1/ios/Classes/HealthPlugin.m:1:8
```

Is there a way around this so we can keep `use_frameworks!` and still use the `mdsflutter` package?

**Comment by bardram** [comment]
@petri-lipponen-movesense @petri-lipponen-suunto - any chance you can look at this. This issue is preventing us from building our iOS app and releasing it to the Apple App Store.... Thanks.

**Comment by petri-lipponen-movesense** [comment]
I'm not too familiar with the use_frameworks!. I know that it was required with older MDS version to make it work. Have you tried it without it using the latest MDS (3.15.0)?

**Comment by SlimShadyIAm** [comment]
Trying to build with `use_frameworks!` throws this error:

```
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): Undefined symbol: _OBJC_CLASS_$_MDSWrapper


Error (Xcode): Linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SlimShadyIAm** [comment]
> I'm not too familiar with the use_frameworks!. I know that it was required with older MDS version to make it work. Have you tried it without it using the latest MDS (3.15.0)?

The current instructions say to remove `use_frameworks!`, otherwise it will fail with the above error.

**Comment by petri-lipponen-movesense** [comment]
Please look at the solution here:

https://bitbucket.org/movesense/movesense-mobile-lib/issues/119/cannot-use-health-and-mdsflutter-depending
