### ISSUE TITLE
OnDisconnect callback is triggered multiple times  

### ISSUE THREAD

**Issue by 84rrry** [petri-lipponen-movesense/mdsflutter#19]
I'm facing an issue where the OnDisconnect callback is being called multiple times when the user turns off the Bluetooth manually while sensors are connected. This doesn't occur when i programmatically disconnect the sensors. 
I'm using 
`- mdsFlutter : 2.0.0
- mdslib : 3.15.0`

**Comment by petri-lipponen-movesense** [comment]
Is it possible that your app is calling connect multiple times for the same sensor? The correct use is to call it once, and then just listen to the callbacks.

**Comment by petri-lipponen-movesense** [comment]
If the reason was multiple connect calls, this was fixed in 2.1.0. Closing this issue. Please re-open if it happens with latest release.

**Comment by 84rrry** [comment]
Greetings , unfortunately the issue still persist even after updating mdsflutter to latest version and upgraded the mobile mds lib to 3.27.0
