### ISSUE TITLE
Give information about reason to connection error!

### ISSUE THREAD

**Issue by abbjetmus** [petri-lipponen-movesense/mdsflutter#20]
It would be nice if if Mdsflutter could give som information for the connection error. Sometimes the sensor appears on scan but can't connect.

![image](https://github.com/petri-lipponen-movesense/mdsflutter/assets/65755086/1ff3e544-dd60-4a26-877e-337602c0f8b7)

**Comment by petri-lipponen-movesense** [comment]
Good idea. Will be implemented shortly with another fix.

**Comment by petri-lipponen-movesense** [comment]
Fix is in 2.0.1-beta2. Will release 2.0.1 when tested more thoroughly.

**Comment by petri-lipponen-movesense** [comment]
Implemented in 2.1.0
