### ISSUE TITLE
Missing namespace in the build.gradle file for the :mdsflutter module. 

### ISSUE THREAD

**Issue by AravindhKnightDev** [petri-lipponen-movesense/mdsflutter#26]
Failed to query the value of property 'buildFlowServiceProperty'.
> Could not isolate value org.jetbrains.kotlin.gradle.plugin.statistics.BuildFlowService$Parameters_Decorated@34f7ca3f of type BuildFlowService.Parameters
   > A problem occurred configuring project ':mdsflutter'.
      > Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
         > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

Plugin gradle is the problem.
Need to upgrade in latest version.
Kindly update namespace in the build.gradle.

**Comment by 84rrry** [comment]
I made a pr fixing this issue. @petri-lipponen-movesense can you please check it!

**Comment by petri-lipponen-movesense** [comment]
Fixed in 2.1.2
